### ISSUE TITLE
Change project name

### ISSUE THREAD

**Issue by koluacik** [ucanyiit/YATSIM#1]
It would be a good idea to change the project name to a more descriptive name if it is going to be publicly available.

We can list names we have come up with in this issue. A name fitting the general theme ("trains", "simulation", "game", etc.) would be nice.

On the long term, we can even design a logo for the application!

Some of the names I've come up with:
- YATS (Yet Another Train Simulator): (https://www.acronymfinder.com/YATS.html)
- YATSIM: (https://www.acronymfinder.com/Yet-Another-TLM-(Transmission-Line-Matrix)-Simulator-(software)-(YATSIM).html)
- Trasim FE (Train Simulator For Everyone): **Not used**

**Comment by ucanyiit** [comment]
We have agreed on the name "YATSIM" and changed the project name.
